service: user-api

provider:
  name: aws
  runtime: python3.12
  region: us-west-1
  environment:
    TABLE_NAME: users-anthony

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-anthony
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

functions:
  saveUser:
    handler: saveUser/index.handler
    events:
      - http:
          path: saveUser
          method: post

  getUser:
    handler: getUser/index.handler
    events:
      - http:
          path: getUser
          method: get
